apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-replicaset
  name: nginx-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources: {}
